apiVersion: v1
kind: ConfigMap
metadata:
  name: tester-cm
#  namespace: openshift-test-runner
data:
  build.tester.sh: |-
    #!/usr/bin/bash

    export GOPATH=/tmp/go
    wkDir=${GOPATH}/src/github.com/origin
    mkdir -p ${wkDir}
    cd ${wkDir}

    ## the depth makes the checkout faster by not bringing all of the history.
    git clone --depth=1 --branch ${gitBranch} ${gitRepo} ./

    make build WHAT=cmd/openshift-tests

    cp ${wkDir}/_output/local/bin/linux/$(go env GOARCH)/openshift-tests /tmp/tester-bin/openshift-tests
