apiVersion: v1
kind: ConfigMap
metadata:
  name: tester-cm
  namespace: openshift-test-runner
data:
  build.tester.sh: |-
    #!/usr/bin/bash

    export GOPATH=/tmp/go
    wkDir=${GOPATH}/src/github.com
    
    echo "setting up working directory ${wkDir}"
    mkdir -p ${wkDir}
    cd ${wkDir}

    echo "checking out ${gitRepo} on branch ${gitBranch}"
    git clone --branch ${gitBranch} ${gitRepo}

    cd origin

    echo "Building openshift-tests"
    make build WHAT=cmd/openshift-tests

    cp ${wkDir}/origin/_output/local/bin/linux/$(go env GOARCH)/openshift-tests /tmp/tester-bin/openshift-tests
